<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php
        echo $this->headTitle('Veselata - ' . $this->translate('Welcome'))
                ->setSeparator(' - ')
                ->setAutoEscape(false);
        ?>

        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/admin.css')
                ->prependStylesheet($this->basePath() . '/libs/bootstrap/dist/css/bootstrap.css');
        ?>

    </head>
    <body>
        <header>
            <nav><a href="<?php echo $this->url('dashboard'); ?>"><img src="<?php echo $this->basePath() . '/images/logo.png'; ?>" alt="Veselata" /></a></nav>
            <aside><?php echo $this->partial('partial/logged', array('identity' => $identity)); ?></aside>
        </header>
        <section>
            <aside><?php echo $this->navigation('navigation')->menu()->escapeLabels(false); ?></aside>
            <?php echo $this->content; ?>
        </section>
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/libs/jquery/dist/jquery.min.js')
                ->prependFile($this->basePath() . '/libs/bootstrap/dist/bootstrap.min.js');
        ?>
    </body>
</html>