<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php
        echo $this->headTitle('Veselata - ' . $this->translate('Welcome'))
                ->setSeparator(' - ')
                ->setAutoEscape(false);
        ?>

        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/admin.css')
                ->prependStylesheet($this->basePath() . '/libs/bootstrap/dist/css/bootstrap.css')
                ->prependStylesheet($this->basePath() . '/libs/jquery-bootgrid/dist/jquery.bootgrid.min.css');
        ?>

    </head>
    <body>
        <div class="container">
            <header>
                <nav class="col-md-3"><a href="<?php echo $this->url('dashboard'); ?>"><img src="<?php echo $this->basePath() . '/images/logo.png'; ?>" alt="Veselata" /></a></nav>
                <aside class="col-md-9"><?php echo $this->partial('partial/logged', array('identity' => $identity)); ?></aside>
            </header>
            <section class="row">
                <nav class="col-md-offset-3"><?php echo $this->navigation('navigation')->breadcrumbs()->setPartial('partial/breadcrumbs')->setMinDepth(0)->setRenderInvisible(); ?></nav>
                <aside class="col-md-3"><?php echo $this->navigation('navigation')->menu()->escapeLabels(false); ?></aside>
                <div class="col-md-9"><?php echo $this->content; ?></div>
            </section>
        </div>
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/admin.js')
                ->prependFile($this->basePath() . '/libs/ckfinder/ckfinder.js')
                ->prependFile($this->basePath() . '/libs/ckeditor/ckeditor.js')
                ->prependFile($this->basePath() . '/libs/jquery-bootgrid/dist/jquery.bootgrid.min.js')
                ->prependFile($this->basePath() . '/libs/bootstrap/dist/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/libs/jquery/dist/jquery.min.js');
        ?>
    </body>
</html>