<h5><?php echo $this->translate('Find me'); ?></h5>
<ul class="aside-social clearfix">
    <li>
        <a class="btn btn-social-icon btn-github">
            <i class="fa fa-github"></i>
        </a>
    </li>
    <li>
        <a class="btn btn-social-icon btn-google-plus">
            <i class="fa fa-google-plus"></i>

        </a>
    </li>
    <li>
        <a class="btn btn-social-icon btn-linkedin">
            <i class="fa fa-linkedin"></i>
        </a>
    </li>
    <li>
        <a class="btn btn-social-icon btn-twitter">
            <i class="fa fa-twitter"></i>
        </a>
    </li>
</ul>
