<h1>List</h1>
<p><a href="<?php echo $this->url('boxes', array('action' => 'add')); ?>" class="btn btn-primary">Add</a></p>
<?php echo $this->flashMessenger()->render(); ?>
<table id="base-grid" data-url="/api/boxes" class="table table-condensed table-hover table-striped">
    <thead>
        <tr>
            <th data-column-id="title">Title</th>
            <th data-column-id="position">Position</th>
            <th data-column-id="status">Status</th>
            <th data-column-id="options" data-formatter="options" data-sortable="false">Options</th>
        </tr>
    </thead>
</table>