<div class="panel panel-default">
    <div class="panel-heading clearfix">
        <h4 class="pull-left">Boxes List</h4>
        <span class="pull-right">
            <a href="<?php echo $this->url('boxes', array('action' => 'add')); ?>" class="btn btn-default">Add</a>
        </span>
    </div>
    <div class="panel-body">
        <?php echo $this->alerts()->render(); ?>
        <table id="base-grid" data-url="/api/boxes" class="table table-condensed table-hover table-striped">
            <thead>
                <tr>
                    <th data-column-id="title">Title</th>
                    <th data-column-id="position">Position</th>
                    <th data-column-id="status">Status</th>
                    <th data-column-id="options" data-formatter="options" data-sortable="false">Options</th>
                </tr>
            </thead>
        </table>
    </div>
</div>