<div class="panel">
    <div class="panel-heading clearfix">
        <h4 class="pull-left">View contact</h4>
        <span class="pull-right">
            <a href="<?php echo $this->url('contacts', array('action' => 'index')); ?>" class="btn btn-outline btn-default">Back</a>
        </span>
    </div>
    <div class="panel-body">
        <table class="table table-condensed table-hover">
            <tbody>
                <tr><td>Name</td><td><?php echo $object->getName(); ?></td></tr>
                <tr><td>Email</td><td><?php echo $object->getEmail(); ?></td></tr>
                <tr><td>Subject</td><td><?php echo $object->getSubject(); ?></td></tr>
                <tr><td>Message</td><td><?php echo $object->getMessage(); ?></td></tr>
                <tr><td>Ip</td><td><?php echo $object->getIp(); ?></td></tr>
                <tr><td>Date</td><td><?php print_r($object->getCreatedAt()); ?></td></tr>
            </tbody>
        </table>
    </div>
</div>

