<div class="panel panel-default">
    <div class="panel-heading clearfix">
        <h4 class="pull-left">Contact List</h4>
    </div>
    <div class="panel-body">
        <?php echo $this->alerts()->render(); ?>
        <table id="base-grid" data-url="/api/contacts" class="table table-condensed table-hover table-striped">
            <thead>
                <tr>
                    <th data-column-id="name">Name</th>
                    <th data-column-id="email">Email</th>
                    <th data-column-id="ip">Ip</th>
                    <th data-column-id="options" data-formatter="options" data-sortable="false">Options</th>
                </tr>
            </thead>
        </table>
    </div>
</div>