<ul class="breadcrumb">
    <li><a href="<?php echo $this->url('adminarea'); ?>"><?php echo $this->translate('Home'); ?></a></li>
    <?php
    $all = count($this->pages);
    $counter = 1;
    foreach ($this->pages as $page):
        ?>
        <?php if ($page->isActive() && $counter == $all): ?>
            <li class="active"><?php echo strip_tags($page->getLabel()); ?></li>
            <?php else: ?>
            <li><a href="<?php echo $page->getHref(); ?>"><?php echo strip_tags($page->getLabel()); ?></a></li>
        <?php endif; ?>
        <?php $counter++; ?>

    <?php endforeach ?>
</ul>
