
<table id="base-grid" data-url="/api/users" class="table table-condensed table-hover table-striped">
    <thead>
        <tr>
            <th data-column-id="id">ID</th>
            <th data-column-id="name">Name</th>
            <th data-column-id="username">Username</th>
            <th data-column-id="options" data-formatter="options" data-sortable="false">Options</th>
        </tr>
    </thead>
</table>