<h1>List</h1>
<p><a href="<?php echo $this->url('users', array('action' => 'add')); ?>" class="btn btn-primary">Add</a></p>
<?php echo $this->flashMessenger()->render(); ?>
<table id="base-grid" data-url="/api/users" class="table table-condensed table-hover table-striped">
    <thead>
        <tr>
            <!--th data-column-id="id" data-type="numeric" data-visible="false">ID</th-->
            <th data-column-id="name">Name</th>
            <th data-column-id="username">Username</th>
            <th data-column-id="type">Type</th>
            <th data-column-id="status">Status</th>
            <th data-column-id="options" data-formatter="options" data-sortable="false">Options</th>
        </tr>
    </thead>
</table>