<div class="panel panel-default">
    <div class="panel-heading clearfix">
        <h4 class="pull-left">Users list</h4>
        <span class="pull-right">
            <a href="<?php echo $this->url('users', array('action' => 'add')); ?>" class="btn btn-success">Add</a>
        </span>
    </div>
    <div class="panel-body">
        <?php echo $this->alerts()->render(); ?>
        <table id="base-grid" data-url="/api/users" class="table table-condensed table-hover table-striped">
            <thead>
                <tr>
                    <!--th data-column-id="id" data-type="numeric" data-visible="false">ID</th-->
                    <th data-column-id="name">Name</th>
                    <th data-column-id="username">Username</th>
                    <th data-column-id="type">Type</th>
                    <th data-column-id="status">Status</th>
                    <th data-column-id="options" data-formatter="options" data-sortable="false">Options</th>
                </tr>
            </thead>
        </table>
    </div>
</div>